name: tour_maker
version: 1.2.8+2
publish_to: none
description: A new Flutter project.
environment:

  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.1
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  date_time_picker: ^2.1.0
  dio: ^5.0.1
  expansion_tile_card: ^3.0.0
  firebase_admin: ^0.2.0
  firebase_app_check: ^0.1.1+8
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.5
  firebase_performance: ^0.9.2+2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^14.0.0+2
  flutter_svg: ^2.0.0+1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_cli: ^1.8.1
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  http: ^0.13.5
  http_parser: ^4.0.2
  image_picker: ^0.8.6+1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  liquid_pull_to_refresh: ^3.0.1
  path_provider: ^2.0.13
  pretty_dio_logger: ^1.1.1
  razorpay_flutter: ^1.3.4
  share_plus: ^5.0.0
  shared_preferences: ^2.1.0
  shimmer: ^3.0.0
  sizer: ^2.0.15
  sms_autofill: ^2.2.0
  syncfusion_flutter_pdfviewer: ^21.1.41
  timer_count_down: ^2.2.2
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/Logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: TourMaker
      fonts:
        - asset: assets/TourMaker.ttf
    - family: Mesa
      fonts:
        - asset: fonts/Mesa Grande.ttf
